books/urls.py
from django.urls import path
from .import views

app_name='books'

urlpatterns = [
	path('',views.index, name='index'),
	path('addbook', views.addbook, name='addbook'),
	path('editbook/<int:pk>', views.editbook, name='editbook'),
	path('downloadcsv',views.downloadcsv,name='downloadcsv'),
]

dceastlibmanagement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls'),name='homepage'),
    path('books/',include('books.urls'),name='books'),
    path('authors/',include('authors.urls'),name='authors'),
    path('publisher/',include('publisher.urls'),name='publisher'),
    path('accompanyingmaterials/',include('accompanyingmaterials.urls'),name='accompanyingmaterials'),
    path('vendor/',include('vendor.urls'),name='vendor'),
    path('bindingtypes/',include('bindingtypes.urls'),name='bindingtypes'),
    path('doctypes/',include('doctypes.urls'), name='doctypes'),
    path('collectiontype/',include('collectiontype.urls'),name='collectiontype'),
    path('login/',include('loginpage.urls'), name='login'),
    path('modeofacqisition/',include('modeofacqisition.urls'), name='modeofacqisition'),
    path('members/',include('members.urls'),name='members'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
	path('',views.index,name='index'),
	path('issuebook', views.issuebook,name='issuebook'),
	path('viewpast', views.viewpast, name='viewpast'),
	path('renewdate',views.renewdate, name='renewdate'),
	path('searchbooks',views.searchbooks, name='searchbooks'),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render, redirect
from accounts.models import *
from django.contrib.auth.decorators import login_required
from books.forms import IssueForm
from django.http import HttpResponse
from datetime import date
from django.db.models import Q
from django.core.paginator import Paginator
from django.core.paginator import Paginator

@login_required(login_url='/login/')
def index(request):
	if request.method == 'POST':
		issuedbook = Issue.objects.get(pk=request.POST['pk'])
		issuedbook.returned = True
		issuedbook.remark_return = request.POST['remark_return']
		issuedbook.save()
		return redirect('/')
	pastissuedbooks = Issue.objects.filter(returned=False).filter(return_date__lt=date.today())
	todayreturn = Issue.objects.filter(returned=False).filter(return_date=date.today())
	issuedbooks = Issue.objects.filter(returned=False).exclude(return_date=date.today()).exclude(return_date__lt=date.today())
	context = {'issuedbooks':issuedbooks,'todayreturn':todayreturn,'pastissuedbooks':pastissuedbooks}
	return render(request,'homepage/index.html',context)

@login_required(login_url='/login/')
def issuebook(request):
	if request.method == 'POST':
		postrequest = request.POST
		postrequest._mutable = True
		# postrequest['issue_date'] = date.today()
		postrequest['issued_by'] = request.user
		form = IssueForm(postrequest)
		if form.is_valid():
			form.save()
		else:
			return HttpResponse(str(form.errors))
		return redirect('/')
	# books = Book.objects.all()
	return render(request,'homepage/issuebook.html')

@login_required(login_url='/login/')
def viewpast(request):
	issuedbooks = Issue.objects.filter(returned=True)
	paginator = Paginator(issuedbooks, 15)
	page = request.GET.get('page')
	issuedbooks = paginator.get_page(page)
	context ={'issuedbooks':issuedbooks,'paginationdata':issuedbooks}
	return render(request,'homepage/pastissuedbooks.html',context)

@login_required(login_url='/login/')
def renewdate(request):
	issuedbook = Issue.objects.get(pk=request.POST['pk'])
	issuedbook.return_date = request.POST['renewdate']
	issuedbook.save()
	return redirect('/')

# @login_required(login_url='/login/')
# def searchbooks(request):
# 	books = Book.objects.all()
# 	paginator = Paginator(books, 12)
# 	page = request.GET.get('page')
# 	books = paginator.get_page(page)
# 	# context = getcontext()
# 	context = {}
# 	context['books'] = context['paginationdata'] = books
# 	return render(request,'homepage/searchbooks.html',{'books':books})

def getcontext():
	context = {
		'authors' : Author.objects.all().order_by('author_name'),
		'accmaterials' : AccompanyingMaterials.objects.all(),
		'vendors' : Vendor.objects.all(),
		'bindingtypes':BindingType.objects.all(),
		'doctypes': DocumentType.objects.all(),
		'typeofcollections' : TypeOfCollection.objects.all(),
		'publishers': Publisher.objects.all(),
		'modeofacquisitions':ModeOfAccuisition.objects.all(),
	}
	return context

def booksearchcondition(request,listofval):
	for l in listofval:
		if request.GET.get(l):
			return True
	return False
	# request.GET.get('author')or request.GET.get('publisher')or request.GET.get('title') or request.GET.get('year')	

@login_required(login_url='/login/')
def searchbooks(request):
	books = Book.objects.all().order_by('accession_number')
	listofval = ['author','publisher','title','year','accession_number']
	if (booksearchcondition(request,listofval)):
		if request.GET.get('title'):
			books = books.filter(title__icontains=request.GET.get('title'))
		if request.GET.get('year'):
			books = books.filter(year__icontains=request.GET.get('year'))
		if request.GET.get('publisher'):
			books = books.filter(publisher__pub_name__icontains=request.GET.get('publisher'))
		if request.GET.get('author'):
			books = books.filter(author__author_name__icontains=request.GET.get('author'))
		if request.GET.get('accession_number'):
			books = books.filter(accession_number__icontains=request.GET.get('accession_number'))
	paginator = Paginator(books, 12)
	page = request.GET.get('page')
	books = paginator.get_page(page)
	context = getcontext()
	context['books'] = context['paginationdata'] = books
	return render(request,'homepage/searchbooks.html',context)

homepage/templates/homepage/index.html
{% extends 'base.html' %}
{% block title %}Issue Books{% endblock %}
{% block body %}

<div class="container">
	<div class="row text-center">
		<div class="col-lg-6 col-md-6">
			<h4><a href="{% url 'homepage:issuebook' %}" class="btn btn-info">Issue Book</a></h4>
		</div>
		<div class="col-lg-6 col-md-6">
			<h5><a href="{% url 'homepage:viewpast' %}" class="btn btn-primary">View past issued books</a></h5>
		</div>
	</div>
</div>
{% if pastissuedbooks %}
	<h4 class="text-center">Books past due date</h4>
	<table class="table container text-center">
		<thead class="table-dark">
			<tr>
				<th>Book Title</th>
				<th>Member Name</th>
				<th>Member Number</th>
				<th>Issue Date</th>
				<th>Return Date</th>
				<th>Issued By</th>
				<th></th>
			</tr>
		</thead>
			{% for past in pastissuedbooks %}
				<tr>
					<td>{{ past.book }}</td>
					<td>{{ past.member_name }}</td>
					<td>{{ past.member_number|default:'' }}</td>
					<td>{{ past.issue_date }}</td>
					<td>{{ past.return_date }}</td>
					<td>{{ past.issued_by }}</td>
					<td>
						<button type="button" class="btn btn-outline-info btn-sm" data-bs-toggle="modal" data-bs-target="#renewModal" onclick="addpkrenew('{{ past.pk }}','{{ past.book }}')">Renew</button>
						<button type="button" class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#staticBackdrop" onclick="addpk('{{ past.pk }}','{{ past.book }}')">Return</button>
					</td>
				</tr>
			{% endfor %}
	</table>
{% endif %}
<br>
{% if todayreturn %}
	<h4 class="text-center">Books to be returned today</h4>
	<table class="table container text-center">
		<thead class="table-dark">
			<tr>
				<th>Book Title</th>
				<th>Member Name</th>
				<th>Member Number</th>
				<th>Issue Date</th>
				<th>Return Date</th>
				<th>Issued By</th>
				<th></th>
			</tr>
		</thead>
		{% for today in todayreturn %}
			<tr>
				<td>{{ today.book }}</td>
				<td>{{ today.member_name }}</td>
				<td>{{ today.member_number|default:'' }}</td>
				<td>{{ today.issue_date }}</td>
				<td>{{ today.return_date }}</td>
				<td>{{ today.issued_by }}</td>
				<td>
					<button type="button" class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#staticBackdrop" onclick="addpk('{{ today.pk }}','{{ today.book }}')">Return</button>
				</td>
			</tr>
		{% endfor %}
	</table>
{% endif %}
<br>
{% if issuedbooks %}
	<h4 class="text-center">Other Issued</h4>
	<table class="table container text-center">
		<thead class="table-dark">
			<tr>
				<th>Book Title</th>
				<th>Member Name</th>
				<th>Member Number</th>
				<th>Issue Date</th>
				<th>Return Date</th>
				<th>Issued By</th>
				<th></th>
			</tr>
		</thead>
		{% for issuedbook in issuedbooks %}
			<tr>
				<td>{{ issuedbook.book }}</td>
				<td>{{ issuedbook.member_name }}</td>
				<td>{{ issuedbook.member_number|default:'' }}</td>
				<td>{{ issuedbook.issue_date }}</td>
				<td>{{ issuedbook.return_date|default:'' }}</td>
				<td>{{ issuedbook.issued_by }}</td>
				<td>
					<button type="button" class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#staticBackdrop" onclick="addpk('{{ issuedbook.pk }}','{{ issuedbook.book }}')">Return</button>
				</td>
			</tr>
		{% endfor %}
	</table>
{% endif %}
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="returntitle"></h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<form method="post">
				<table class="table" class="text-center">
					{% csrf_token %}
					<input type="hidden" name="pk" id="pk">
					<tr>
						<td colspan="2"><textarea name="remark_return" cols="30" rows="5" class="form-control" placeholder="remarks"></textarea></td>
					</tr>
					<tr><td><input type="submit" class="btn btn-outline-success btn-sm"></td></tr>
				</table>
				</form>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="renewModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="renewtitle"></h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<form method="post" action="{% url 'homepage:renewdate' %}">
				<table class="table" class="text-center">
					{% csrf_token %}
					<input type="hidden" name="pk" id="pk2">
					<tr>
						<td>Renew Date</td>
						<td><input type="date" class="form-control" name="renewdate"></td>
					</tr>
					<tr><td colspan="2"><input type="submit" class="btn btn-outline-success btn-sm"></td></tr>
				</table>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
	function addpk(pk, bookname){
		$('#returntitle').text(bookname)
		$('#pk').val(pk)
	}
	function addpkrenew(pk, bookname){
		// alert(bookname)
		$('#renewtitle').text(bookname)
		$('#pk2').val(pk)
	}
</script>
{% endblock %}

homepage/templates/homepage/issuebook.html
{% extends 'base.html' %}
{% block body %}
<style>
	.required:after{
		color: red;
		content: " *";
	}
	.required2{
		color: red;
	}
</style>
<br><br>
<table class="table container text-center">
	<form method="post">
		{% csrf_token %}
	<tr>
		<td class="required">Book</td>
		<td class="input-group">
			<input type="text" name="book" class="form-control" id="id_book">
			<input type="text" class="form-control" id="id_book_title">
			<button type="button" class="btn btn-outline-success" onclick="openwindow()">Search for books</button>
		</td>
	</tr>
	<tr>
		<td class="required">Member Name</td>
		<td><input type="text" class="form-control" name="member_name" maxlength="300" required></td>
	</tr>
	<tr>
		<td>Member Number</td>
		<td><input type="text" class="form-control" name="member_number"></td>
	</tr>
	<tr>
		<td class="required">Issue Date</td>
		<td><input type="date" class="form-control" name="issue_date" required></td>
	</tr>
	<tr>
		<td>Return Date</td>
		<td><input type="date" class="form-control" name="return_date"></td>
	</tr>
	<tr>
		<td colspan="2"><input type="submit" class="btn btn-outline-success"></td>
	</tr>
	</form>
</table>
<script>
	function openwindow(){
		var myWindow = window.open("{% url 'homepage:searchbooks' %}", "myWindow");
	}
</script>
{% endblock %}

homepage/templates/homepage/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	
</body>
</html>

homepage/templates/homepage/pastissuedbooks.html
{% extends 'base.html' %}
{% block body %}

<table class="table container text-center table-bordered">
	<tr>
		<td colspan="7"><h4>Past books Issued</h4></td>
	</tr>
	<tr>
		<th>Book Title</th>
		<th>Member Name</th>
		<th>Member Number</th>
		<th>Issue Date</th>
		<th>Return Date</th>
		<th>remark</th>
		<th>Issued By</th>
	</tr>
	{% for issuedbook in issuedbooks %}
		<tr>
			<td>{{ issuedbook.book }}</td>
			<td>{{ issuedbook.member_name }}</td>
			<td>{{ issuedbook.member_number|default:'' }}</td>
			<td>{{ issuedbook.issue_date }}</td>
			<td>{{ issuedbook.return_date|default:'' }}</td>
			<td>{{ issuedbook.remark_return }}</td>
			<td>{{ issuedbook.issued_by }}</td>
		</tr>
	{% endfor %}
</table>

{% include 'pagination.html' %}


{% endblock %}

homepage/templates/homepage/searchbooks.html
{% extends 'base.html' %}
{% block title %}Books{% endblock %}
{% block body %}
<style>
	div form input,select,button{
		margin-top: 10px;
	}
</style>
<table class="table container text-center table-sm">
	<tr>
		<th colspan="5">
			<button class="btn btn-outline-info" data-bs-toggle="modal" data-bs-target="#exampleModal">Search Books</button>
		</td>
	</tr>
	{% if books %}
	<tr>
		<th>Accession</th>
		<th>Title</th>
		<th>Publisher</th>
		<th>Author</th>
		<th>Year of Publication</th>
		<th></th>
	</tr>
	{% endif %}
	{% for book in books %}
	<tr>
		<td>{{ book.accession_number|default:'' }}</td>
		<td>{{ book.title }}</td>
		<td>{{ book.publisher|title }}</td>
		<td>{{ book.author.all|join:', '|title }}</td>
		<td>{{ book.year }}</td>
		<td><button type="button" class="btn btn-outline-info btn-sm" onclick="ChangeOpener('{{ book.pk }}','{{ book.title }}')">Select</button></td>
	</tr>
	{% endfor %}
</table>

{% include 'pagination.html' %}
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Search Using</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<form class="text-center">
					<input type="text" name="title" placeholder="title" class="form-control">
					<input type="text" name="year" placeholder="year of publication" class="form-control">
					<input type="text" name="accession_number" placeholder="accession number" class="form-control">
					<select name="publisher" class="form-control">
						<option value="">-- select publisher --</option>
						{% for publisher in publishers %}
						<option value="{{ publisher.pub_name|title }}" {% if publisher.pub_name|title == request.GET.publisher|title %}selected{% endif %}>{{ publisher.pub_name|title }}</option>
						{% endfor %}
					</select>
					<select name="author" class="form-control">
						<option value="">-- select author --</option>
						{% for author in authors %}
						<option value="{{ author.author_name|title }}" {% if author.author_name|title == request.GET.author|title %}selected{% endif %}>{{ author.author_name|title }}</option>
						{% endfor %}
					</select>
					<input onclick="removeview()" type="submit" class="btn btn-outline-success btn-sm">
				</form>
			</div>
		</div>
	</div>
</div>
<script>
	function ChangeOpener (id_book,id_book_title) {
		var openerWindow = window.opener;
		openerWindow.document.getElementById("id_book").value=id_book;
		openerWindow.document.getElementById("id_book_title").value=id_book_title;
		window.close();
		return;
	}

</script>
{% endblock %}