books/urls.py
from django.urls import path
from .import views

app_name='books'

urlpatterns = [
	path('',views.index, name='index'),
	path('addbook', views.addbook, name='addbook'),
	path('editbook/<int:pk>', views.editbook, name='editbook'),
	path('downloadcsv',views.downloadcsv,name='downloadcsv'),
]

dceastlibmanagement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls'),name='homepage'),
    path('books/',include('books.urls'),name='books'),
    path('authors/',include('authors.urls'),name='authors'),
    path('publisher/',include('publisher.urls'),name='publisher'),
    path('accompanyingmaterials/',include('accompanyingmaterials.urls'),name='accompanyingmaterials'),
    path('vendor/',include('vendor.urls'),name='vendor'),
    path('bindingtypes/',include('bindingtypes.urls'),name='bindingtypes'),
    path('doctypes/',include('doctypes.urls'), name='doctypes'),
    path('collectiontype/',include('collectiontype.urls'),name='collectiontype'),
    path('login/',include('loginpage.urls'), name='login'),
    path('modeofacqisition/',include('modeofacqisition.urls'), name='modeofacqisition'),
    path('members/',include('members.urls'),name='members'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginpage/urls.py
from django.urls import path
from . import views
app_name = 'login'

urlpatterns = [
	path('', views.index, name='index'),
	path('loginuser', views.loginuser, name='loginuser'),
	path('logoutuser', views.logoutuser, name='logoutuser'),
	path('register', views.createuser, name='createuser'),
	path('searchforbook', views.searchforbook, name='searchforbook'),
	path('bookstatus/<int:pk>', views.bookstatus, name='bookstatus'),
	path('changepassword',views.changepassword, name='changepassword'),
]

loginpage/models.py
from django.db import models

# Create your models here.

loginpage/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, get_user_model, logout
from django.contrib import messages
from accounts.models import User, Book, Issue
from books.views import searchbookfunc


def index(request):
	if request.user.is_authenticated:
		return redirect("/")
	return render(request,'loginpage/index.html')

def loginuser(request):
	if request.user.is_authenticated:
		return redirect("/")
	if request.method == 'POST':
		user=authenticate(username=request.POST['username'],password=request.POST['password'])
		if user is not None:
			login(request, user)
			if request.GET.get('next'):
				return redirect(request.GET.get('next'))
			return redirect('/')
		else:
			messages.error(request,'Please check your credentails')
	return render(request,'loginpage/loginuser.html')

def logoutuser(request):
	logout(request)
	return redirect('/')

def createuser(request):
	if request.method == 'POST':
		if request.POST['password1'] != request.POST['password2']:
			messages.error(request,'Passwords dont match')
			return redirect('/login/register')
		if User.objects.filter(username=request.POST['username']):
			messages.error(request,'UserName already present')
			return redirect('/login/register')
		user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
		login(request, user)
		return redirect('/')
	return render(request,'loginpage/createuser.html')

def searchforbook(request):
	books = Book.objects.all().filter(title__icontains=request.GET.get('title'))
	return render(request,'loginpage/searchforbooks.html',{'books':books})

def bookstatus(request,pk):
	book = Book.objects.get(pk=pk)
	issued = Issue.objects.filter(book=book).filter(returned=False)
	if(len(issued)==0):
		issued = 'Available'
	else:
		issued = 'Not Available'
	return render(request,'loginpage/bookstatus.html',{'book':book,'issued':issued})

def changepassword(request):
	if request.method == 'POST':
		if request.POST['password1'] != request.POST['password2']:
			messages.error(request,'Passwords dont match')
		user = User.objects.get(username__exact=request.POST['username'])
		user.set_password(request.POST['password1'])
		user.save()
		messages.success(request,'Password changed')
	return render(request,'loginpage/changepassword.html')

loginpage/templates/loginpage/baselogin.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{% endblock %}</title>
	<!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->
	<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> -->
	<!-- <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script> -->
	{% load static %}
	<link href="{% static 'bootstrap5/css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="{% static 'bootstrap5/js/bootstrap.bundle.min.js' %}" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<script src="{% static 'bootstrap5/jquery.js' %}" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container-fluid">
			<a class="navbar-brand" href="/">D&SC Library Management System</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item">
						
					</li>
				</ul>
				<!-- <a href="{% url 'login:loginuser' %}" class="btn btn-outline-danger">login</a> -->
				<form action="{% url 'login:loginuser' %}">
					<input type="hidden" value="{{ request.GET.next }}" name="next">
					<input type="submit" class="btn btn-outline-danger" value="login">
				</form>
			</div>
		</div>
	</nav>
	{% block body %}
	{% endblock %}
</body>
</html>

loginpage/templates/loginpage/bookstatus.html
{% extends 'loginpage/baselogin.html' %}
{% block title %} {{ book.title }} {% endblock %}
{% block body %}
<br><br>
<table class="table text-center container">
	<tr>
		<td>Title</td>
		<td>{{ book.title }}</td>
	</tr>
	<tr>
		<td>Subtitle</td>
		<td>{{ book.subtitle|default:'' }}</td>
	</tr>
	<tr>
		<td>Author</td>
		<td>{{ book.author.all|join:', '|title }}</td>
	</tr>
	<tr>
		<td>Publisher</td>
		<td>{{ book.publisher|title }}</td>
	</tr>
	<tr>
		<td>Status</td>
		<td>{{ issued }}</td>
	</tr>
</table>

{% endblock %}

loginpage/templates/loginpage/changepassword.html
{% extends 'loginpage/baselogin.html' %}
{% block title %} {{ book.title }} {% endblock %}
{% block body %}
<br><br>
{% if messages %}
		{% for message in messages %}
			<div class="alert alert-{{ message.tags }} alert-dismissible fade show container" role="alert">
  				{{ message }}
  				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
		{% endfor %}
	{% endif %}
<form method="post" class="container">
	{% csrf_token %}
	<input type="text" class="form-control" placeholder="username" name="username"><br>
	<input type="password" class="form-control" placeholder="password" name="password1"><br>
	<input type="password" class="form-control" placeholder="re enter password" name="password2"><br>
	<input type="submit" class="btn btn-outline-success">
</form>

{% endblock %}

loginpage/templates/loginpage/createuser.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Register</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container-fluid">
			<a class="navbar-brand" href="#">D&SC Library Management System</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item">
						
					</li>
				</ul>
				<!-- <a href="{% url 'login:loginuser' %}" class="btn btn-outline-danger">login</a> -->
				<form action="{% url 'login:loginuser' %}">
					<input type="hidden" value="{{ request.GET.next }}" name="next">
					<input type="submit" class="btn btn-outline-danger" value="login">
				</form>
			</div>
		</div>
	</nav>
	{% if messages %}
		{% for message in messages %}
			<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
  				{{ message }}
  				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
		{% endfor %}
	{% endif %}
	<form method="post" class="container" style="margin-top: 50px;">
	<table class="table text-center">
		{% csrf_token %}
		<tr>
			<td><input type="text" class="form-control" name="first_name" placeholder="First Name" maxlength="100" required></td>
		</tr>
		<tr>
			<td><input type="text" class="form-control" name="last_name" placeholder="Last Name" maxlength="100" required></td>
		</tr>
		<tr>
			<td><input type="text" class="form-control" name="username" placeholder="username" maxlength="100" required></td>
		</tr>
		<tr>
			<td><input type="password" class="form-control" name="password1" placeholder="password1" required></td>
		</tr>
		<tr>
			<td><input type="password" class="form-control" name="password2" placeholder="Re enter password" required></td>
		</tr>
		<tr><td><input type="submit" class="btn btn-outline-success"></td></tr>
	</table>
	</form>
</body>
</html>

loginpage/templates/loginpage/index.html
{% extends 'loginpage/baselogin.html' %}
{% block title %}Login Home{% endblock %}
{% block body %}
<form class="container" style="margin-top: 100px;" action="{% url 'login:searchforbook' %}">
	<div class="input-group">
		<input type="text" class="form-control" name="title" placeholder="search book by title">
		<button class="btn btn-success">Search</button>
	</div>
</form>
{% endblock %}

loginpage/templates/loginpage/loginuser.html
{% extends 'loginpage/baselogin.html' %}
{% block body %}
{% if messages %}
		{% for message in messages %}
			<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
  				{{ message }}
  				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
		{% endfor %}
	{% endif %}
	<table class="table container text-center">
		<form method="post">
		{% csrf_token %}
		<input type="hidden" name="next" value="{{ request.GET.next }}">
		<tr>
			<td><input type="text" class="form-control" placeholder="username" name="username"></td>
		</tr>
		<tr>
			<td><input type="password" class="form-control" placeholder="password" name="password"></td>
		</tr>
		<tr>
			<td><input type="submit" class="btn btn-outline-success" value="submit"></td>
		</tr>
		</form>
	</table>

{% endblock %}

loginpage/templates/loginpage/searchforbooks.html
{% extends 'loginpage/baselogin.html' %}
{% block title %}Search Result Login{% endblock %}
{% block body %}

<table class="table container text-center">
	<thead class="table-dark">
		<th>Title</th>
		<th>Author</th>
		<th>Publisher</th>
	</thead>
{% for book in books %}
	<tr>
		<td><a href="{% url 'login:bookstatus' book.pk %}">{{ book.title }}</a></td>
		<td>{{ book.author.all|join:', '|title }}</td>
		<td>{{ book.publisher|title }}</td>
	</tr>
{% endfor %}
</table>
{% endblock %}