books/urls.py
from django.urls import path
from .import views

app_name='books'

urlpatterns = [
	path('',views.index, name='index'),
	path('addbook', views.addbook, name='addbook'),
	path('editbook/<int:pk>', views.editbook, name='editbook'),
	path('downloadcsv',views.downloadcsv,name='downloadcsv'),
]

dceastlibmanagement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls'),name='homepage'),
    path('books/',include('books.urls'),name='books'),
    path('authors/',include('authors.urls'),name='authors'),
    path('publisher/',include('publisher.urls'),name='publisher'),
    path('accompanyingmaterials/',include('accompanyingmaterials.urls'),name='accompanyingmaterials'),
    path('vendor/',include('vendor.urls'),name='vendor'),
    path('bindingtypes/',include('bindingtypes.urls'),name='bindingtypes'),
    path('doctypes/',include('doctypes.urls'), name='doctypes'),
    path('collectiontype/',include('collectiontype.urls'),name='collectiontype'),
    path('login/',include('loginpage.urls'), name='login'),
    path('modeofacqisition/',include('modeofacqisition.urls'), name='modeofacqisition'),
    path('members/',include('members.urls'),name='members'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models

# Create your models here.

books/forms.py
from accounts.models import Book, Issue
from django.forms import ModelForm

class BookForm(ModelForm):
	class Meta:
		model = Book
		fields = '__all__'

class IssueForm(ModelForm):
	class Meta:
		model = Issue
		fields = '__all__'

books/views.py
from django.shortcuts import render, redirect
from accounts.models import *
from .forms import BookForm
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from datetime import date
from django.core.paginator import Paginator
import csv

def getcontext():
	context = {
		'authors' : Author.objects.all().order_by('author_name'),
		'accmaterials' : AccompanyingMaterials.objects.all(),
		'vendors' : Vendor.objects.all(),
		'bindingtypes':BindingType.objects.all(),
		'doctypes': DocumentType.objects.all(),
		'typeofcollections' : TypeOfCollection.objects.all(),
		'publishers': Publisher.objects.all(),
		'modeofacquisitions':ModeOfAccuisition.objects.all(),
	}
	return context

def searchbookfunc(books, request):
	if (request.GET.get('author')or request.GET.get('publisher')) or request.GET.get('title') or (request.GET.get('accessionnum')):
		if request.GET.get('title'):
			books = books.filter(title__icontains=request.GET.get('title'))
		if request.GET.get('accessionnum'):
			books = books.filter(accession_number__icontains=request.GET.get('accessionnum'))
		if request.GET.get('publisher'):
			books = books.filter(publisher__pub_name__icontains=request.GET.get('publisher'))
		if request.GET.get('author'):
			books = books.filter(author__author_name__icontains=request.GET.get('author'))
	return books

@login_required(login_url='/login/')
def index(request):
	books = Book.objects.all().order_by('accession_number')
	books = searchbookfunc(books,request)
	if request.GET.get('showreport'):
		return render(request,'books/viewreport.html',{'books':books})
	paginator = Paginator(books, 12)
	page = request.GET.get('page')
	books = paginator.get_page(page)
	context = getcontext()
	context['books'] = context['paginationdata'] = books
	return render(request,'books/index.html',context)

@login_required(login_url='/login/')
def addbook(request):
	if request.method == 'POST':
		postrequest = request.POST
		postrequest._mutable = True
		postrequest['last_updated_by'] = request.user
		postrequest['added_by'] = request.user
		form = BookForm(postrequest)
		if form.is_valid():
			form.save()
			return redirect('/books/')
		else:
			return HttpResponse(str(form.errors))
	context = getcontext()
	return render(request,'books/bookform.html',context)

@login_required(login_url='/login/')
def editbook(request,pk):
	if request.method == 'POST':
		postrequest = request.POST
		postrequest._mutable = True
		postrequest['last_updated_by'] = request.user
		postrequest['last_updated'] = date.today()
		postrequest['added_by'] = Book.objects.get(pk=pk).added_by
		form = BookForm(postrequest,instance=Book.objects.get(pk=pk))
		if form.is_valid():
			form.save()
			return redirect('/books/')
		else:
			return HttpResponse(str(form.errors))
	context = getcontext()
	context['book'] = Book.objects.get(pk=pk)
	return render(request,'books/bookform.html',context)

def convertauthor(authors):
	a = ''
	for author in authors:
		a += author.author_name+', '
	return a[:-2]

@login_required(login_url='/login/')
def downloadcsv(request):
	response = HttpResponse(
			content_type='text/csv',
			headers={'Content-Disposition': 'attachment; filename="bookdata.csv"'},
		)
	writer = csv.writer(response)
	books = Book.objects.all().order_by('accession_number')
	books = searchbookfunc(books,request)
	writer.writerow(('id','ACCESSION NUMBER','TITLE','SUBTITLE','AUTHOR','EDITION','YEAR','PLACE','PUBLSIHER',
		'NUMBER OF VOLUMES','ACCOMPANYING MATERIALS','ITEM PRICE','VENDOR','INVOICE DATE','INVOICE NUMBER',
		'ACCESSION DATE','TYPE OF BINDING','DOC TYPE','LOCATION','TYPE OF COLLECTION','EDITOR','CEASED',
		'CEASE DATE','MODE OF ACCUSITION','REMARKS'))
	for book in books:
		# return HttpResponse()
		writer.writerow((book.pk,book.accession_number,book.title.title(),book.subtitle,
			convertauthor(book.author.all()),book.edition,book.year,book.place, book.publisher,
			book.num_of_vols,book.accompaning_materials,book.item_price,book.vendor,
			book.invoice_date,book.invoice_number,book.accession_date,book.type_of_binding,
			book.doc_type,book.location,book.type_of_collection,book.editor,
			book.ceased,book.ceases_exist_date,	book.mode_of_accuisition,book.remarks))
	return response

books/templates/books/bookform.html
{% extends 'base.html' %}
{% block title %}Book form{% endblock %}
{% block body %}
<style>
	.required:after{
		color: red;
		content: " *";
	}
	.required2{
		color: red;
	}
</style>
<table class="table container text-center">
	<form method="post">
		{% csrf_token %}
		<tr>
			<td class="required">Title</td>
			<td><input type="text" maxlength="500" class="form-control" name="title" value="{{ book.title }}" required></td>
		</tr>
		<tr>
			<td>Subtitle</td>
			<td><input type="text" maxlength="500" class="form-control" name="subtitle" value="{{ book.subtitle|default:'' }}"></td>
		</tr>
		<tr>
			<td>Authors</td>
			<td><select name="author" class="form-control" multiple>
				{% for author in authors %}
					<option value="{{ author.pk }}" {% if author in book.author.all %}selected{% endif %}>{{ author.author_name }}</option>
				{% endfor %}
			</select></td>
		</tr>
		<tr>
			<td>Edition</td>
			<td><input type="text" name="edition" class="form-control" maxlength="10" value="{{ book.edition|default:'' }}"></td>
		</tr>
		<tr>
			<td>Year</td>
			<td><input type="number" name="year" class="form-control" value="{{ book.year|default:'' }}"></td>
		</tr>
		<tr>
			<td class="required">Place</td>
			<td><input type="text" name="place" class="form-control" maxlength="500" value="{{ book.place |default:''}}" required></td>
		</tr>
		<tr>
			<td>Publisher</td>
			<td>
				<select name="publisher" class="form-control">
					<option value=""> - - select publisher - - </option>
					{% for publisher in publishers %}
						<option value="{{ publisher.pk }}" {% if publisher == book.publisher %} selected {% endif %}>{{ publisher.pub_name }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
		<tr>
			<td>Number of Volumes</td>
			<td><input type="text" name="num_of_vols" class="form-control" value="{{ book.num_of_vols|default:'' }}"></td>
		</tr>
		<tr>
			<td>Accompanying Materials</td>
			<td><select name="accompaning_materials" class="form-control" multiple>
				{% for accmaterial in accmaterials %}
					<option value="{{ accmaterial.pk }}" {% if accmaterial == book.accompaning_materials %} selected {% endif %}>{{ accmaterial.accom_name }}</option>
				{% endfor %}
			</select></td>
		</tr>
		<tr>
			<td>Item Price</td>
			<td><input type="text" name="item_price" class="form-control" value="{{ book.item_price|default:'' }}" ></td>
		</tr>
		<tr>
			<td>vendor</td>
			<td><select name="vendor" class="form-control">
				<option value="">- - select vendor - -</option>
				{% for vendor in vendors %}
					<option value="{{ vendor.pk }}" {% if vendor == book.vendor %} selected {% endif %}>{{ vendor.vendor_name }}</option>
				{% endfor %}
			</select></td>
		</tr>
		<tr>
			<td>Invoice Date</td>
			<td><input type="date" name="invoice_date" class="form-control" value="{{ book.invoice_date|date:'c' }}"></td>
		</tr>
		<tr>
			<td>Invoice Nnumber</td>
			<td><input type="number" name="invoice_number" class="form-control" value="{{ book.invoice_number|default:'' }}"></td>
		</tr>
		<tr>
			<td>Accession Number</td>
			<td><input type="text" name="accession_number" class="form-control" value="{{ book.accession_number|default:'' }}"></td>
		</tr>
		<tr>
			<td>Accession Date</td>
			<td><input type="date" name="accession_date" class="form-control" value="{{ book.accession_date|date:'c' }}"></td>
		</tr>
		<tr>
			<td>Type of binding</td>
			<td><select name="type_of_binding" class="form-control">
				<option value="">- - selected type of binding - -</option>
				{% for bindingtype in bindingtypes %}
					<option value="{{ bindingtype.pk }}" {% if bindingtype == book.type_of_binding %} selected {% endif %}>{{ bindingtype.bindingtypename }}</option>
				{% endfor %}
			</select></td>
		</tr>
		<tr>
			<td>Doctype </td>
			<td>
				<select name="doc_type" class="form-control">
					<option value="">- - select doc type - -</option>
					{% for doctype in doctypes %}
						<option value="{{ doctype.pk }}" {% if doctype == book.doc_type %} selected {% endif %}>{{ doctype.doctype_name }} </option>
					{% endfor %}
				</select>
			</td>
		</tr>
		<tr>
			<td>location</td>
			<td><textarea name="location" cols="30" rows="5"class="form-control">{{ book.location|default:'' }}</textarea></td>
		</tr>
		<tr>
			<td>Type of collection</td>
			<td>
				<select name="type_of_collection" class="form-control">
					<option value="">- - select type of collection - -</option>
					{% for typeofcollection in typeofcollections %}
					<option value="{{ typeofcollection.pk }}" {% if typeofcollection == book.type_of_collection %} selected {% endif %}>{{ typeofcollection.collection_name }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
		<tr>
			<td>Editor</td>
			<td>
				<input type="text" name="editor" class="form-control" value="{{ book.editor|default:'' }}">
			</td>
		</tr>
		<tr>
			<td>mode of Acquisition</td>\
			<td>
				<select name="mode_of_accuisition" class="form-control">
					<option value="">- - select mode of accusitiion - -</option>
					{% for modeofacquisition in modeofacquisitions %}
					<option value="{{ modeofacquisition.pk }}" {% if modeofacquisition == book.mode_of_accuisition %} selected {% endif %}>{{ modeofacquisition.accuisition_name }}</option>
					{% endfor %}
				</select>
			</td>
		</tr>
		<tr>
			<td><label for="id_ceased">Ceased</label></td>
			<td style="text-align: left;"><input type="checkbox" id="id_ceased" name="ceased" {% if book.ceased == True %}checked{% endif %}></td>
		</tr>
		<tr>
			<td>Cease Date</td>
			<td><input type="date" name="ceases_exist_date" class="form-control" value="{{ book.ceases_exist_date|date:'c' }}"></td>
		</tr>
		<tr>
			<td>Remarks</td>
			<td><textarea name="remarks" cols="30" rows="4" class="form-control">{{ book.remarks|default:'' }}</textarea></td>
		</tr>
		<tr>
			<td colspan="2"><button class="btn btn-outline-success">Submit</button></td>
		</tr>
	</form>
</table>

{% endblock %}

books/templates/books/index.html
{% extends 'base.html' %}
{% block title %}Books{% endblock %}
{% block body %}
{% load customfilter %}
<style>
	div form input,select,button{
		margin-top: 10px;
	}
</style>
<table class="table container text-center">
	<tr>
		<th colspan="7">
			<a href="{% url 'books:addbook' %}" class="btn btn-link">Add Books</a>
		</td>
	</tr>
	<tr>
		<th colspan="7">
			<button class="btn btn-outline-info" data-bs-toggle="modal" data-bs-target="#exampleModal">Search Books</button>
			<a href="/books/" class="btn btn-link">Reset Search</a>
			<a href="{% url 'books:downloadcsv' %}?{{ request.get_full_path|csvdownloadurlfix }}">Download csv</a>
		</td>
	</tr>
	{% if books %}
	<tr>
		<th>cat no</th>
		<th>Accession Number</th>
		<th>Title</th>
		<th>Publisher</th>
		<th>Author</th>
		<th>Year of Publication</th>
		<th></th>
	</tr>
	{% endif %}
	{% for book in books %}
	<tr>
		<td>{{ book.pk }}</td>
		<td>{{ book.accession_number|default:'' }}</td>
		<td>{{ book.title }}</td>
		<td>{{ book.publisher|title }}</td>
		<td>{{ book.author.all|join:', '|title }}</td>
		<td>{{ book.year }}</td>
		<td><a href="{% url 'books:editbook' book.pk %}" class="btn btn-outline-primary btn-sm">Edit</a></td>
	</tr>
	{% endfor %}
</table>

{% include 'pagination.html' %}
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Search Using</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<form class="text-center">
					<input type="text" name="title" placeholder="title" class="form-control" value="{{ request.GET.title|default:'' }}">
					<input type="text" name="accessionnum" placeholder="Accession number" class="form-control" value="{{ request.GET.accessionnum|default:'' }}" autocomplete="off">
					<select name="publisher" class="form-control">
						<option value="">-- select publisher --</option>
						{% for publisher in publishers %}
						<option value="{{ publisher.pub_name|title }}" {% if publisher.pub_name|title == request.GET.publisher|title %}selected{% endif %}>{{ publisher.pub_name|title }}</option>
						{% endfor %}
					</select>
					<select name="author" class="form-control">
						<option value="">-- select author --</option>
						{% for author in authors %}
						<option value="{{ author.author_name|title }}" {% if author.author_name|title == request.GET.author|title %}selected{% endif %}>{{ author.author_name|title }}</option>
						{% endfor %}
					</select>
					<input type="hidden" id="showreporthidden" name="showreport">
					<input onclick="removeview()" type="submit" class="btn btn-outline-success btn-sm">
					<button onclick="addview()" class="btn btn-outline-warning btn-sm" formtarget="_blank">View Report</button>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
	function addview(){
		$('#showreporthidden').val('true');
	}
	function removeview(){		
		$('#showreporthidden').val('');
	}
</script>
{% endblock %}

books/templates/books/viewreport.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

	<title>Book Report</title>
	<style>
		@media print {
  @page { margin: 0; }
  body { margin: 1.6cm; }
}
	</style>
</head>
<body>
	<table class="table table-bordered text-center table-sm">
		<tr>
			<th></th>
			<th>Title</th>
			<!-- <th>Subtitle</th> -->
			<th>Author</th>
			<th>Publisher</th>
			<th>Location</th>
			<th>Ceased</th>
		</tr>
	{% for book in books %}
		<tr>
			<td>{{ forloop.counter }}</td>
			<td>{{ book.title }}</td>
			<!-- <td>{{ book.subtitle }}</td> -->
			<td>{{ book.author.all|join:', '|title }}</td>
			<td>{{ book.publisher|title }}</td>
			<td>{{ book.location|title }}</td>
			<td>
				{% if book.ceased == True %}<i class="fa fa-check" aria-hidden="true"></i>{% endif %}
				</td>

		</tr>
	{% endfor %}
	</table>
</body>
</html>