authors/urls.py
from django.urls import path
from .import views

app_name='authors'

urlpatterns = [
	path('',views.index, name='index'),
	path('addauthor', views.addauthor, name='addauthor'),
]

books/urls.py
from django.urls import path
from .import views

app_name='books'

urlpatterns = [
	path('',views.index, name='index'),
	path('addbook', views.addbook, name='addbook'),
	path('editbook/<int:pk>', views.editbook, name='editbook'),
	path('downloadcsv',views.downloadcsv,name='downloadcsv'),
]

dceastlibmanagement/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls'),name='homepage'),
    path('books/',include('books.urls'),name='books'),
    path('authors/',include('authors.urls'),name='authors'),
    path('publisher/',include('publisher.urls'),name='publisher'),
    path('accompanyingmaterials/',include('accompanyingmaterials.urls'),name='accompanyingmaterials'),
    path('vendor/',include('vendor.urls'),name='vendor'),
    path('bindingtypes/',include('bindingtypes.urls'),name='bindingtypes'),
    path('doctypes/',include('doctypes.urls'), name='doctypes'),
    path('collectiontype/',include('collectiontype.urls'),name='collectiontype'),
    path('login/',include('loginpage.urls'), name='login'),
    path('modeofacqisition/',include('modeofacqisition.urls'), name='modeofacqisition'),
    path('members/',include('members.urls'),name='members'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctypes/urls.py
from django.urls import path
from .import views

app_name='doctypes'

urlpatterns = [
	path('',views.index, name='index'),
	path('doctypeadd', views.doctypeadd, name='doctypeadd'),
	
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
	path('',views.index,name='index'),
	path('issuebook', views.issuebook,name='issuebook'),
	path('viewpast', views.viewpast, name='viewpast'),
	path('renewdate',views.renewdate, name='renewdate'),
	path('searchbooks',views.searchbooks, name='searchbooks'),
]

loginpage/urls.py
from django.urls import path
from . import views
app_name = 'login'

urlpatterns = [
	path('', views.index, name='index'),
	path('loginuser', views.loginuser, name='loginuser'),
	path('logoutuser', views.logoutuser, name='logoutuser'),
	path('register', views.createuser, name='createuser'),
	path('searchforbook', views.searchforbook, name='searchforbook'),
	path('bookstatus/<int:pk>', views.bookstatus, name='bookstatus'),
	path('changepassword',views.changepassword, name='changepassword'),
]

members/urls.py
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
	path('', views.index,name='index'),
	path('addmember', views.addmember, name='addmember'),
	path('view/<int:pk>',views.viewmember, name='viewmember'),
	path('printcard/<int:pk>',views.printcard,name='printcard'),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render, redirect
from accounts.models import *
from django.contrib.auth.decorators import login_required
from books.forms import IssueForm
from django.http import HttpResponse
from datetime import date
from django.db.models import Q
from django.core.paginator import Paginator
from django.core.paginator import Paginator

@login_required(login_url='/login/')
def index(request):
	if request.method == 'POST':
		issuedbook = Issue.objects.get(pk=request.POST['pk'])
		issuedbook.returned = True
		issuedbook.remark_return = request.POST['remark_return']
		issuedbook.save()
		return redirect('/')
	pastissuedbooks = Issue.objects.filter(returned=False).filter(return_date__lt=date.today())
	todayreturn = Issue.objects.filter(returned=False).filter(return_date=date.today())
	issuedbooks = Issue.objects.filter(returned=False).exclude(return_date=date.today()).exclude(return_date__lt=date.today())
	context = {'issuedbooks':issuedbooks,'todayreturn':todayreturn,'pastissuedbooks':pastissuedbooks}
	return render(request,'homepage/index.html',context)

@login_required(login_url='/login/')
def issuebook(request):
	if request.method == 'POST':
		postrequest = request.POST
		postrequest._mutable = True
		# postrequest['issue_date'] = date.today()
		postrequest['issued_by'] = request.user
		form = IssueForm(postrequest)
		if form.is_valid():
			form.save()
		else:
			return HttpResponse(str(form.errors))
		return redirect('/')
	# books = Book.objects.all()
	return render(request,'homepage/issuebook.html')

@login_required(login_url='/login/')
def viewpast(request):
	issuedbooks = Issue.objects.filter(returned=True)
	paginator = Paginator(issuedbooks, 15)
	page = request.GET.get('page')
	issuedbooks = paginator.get_page(page)
	context ={'issuedbooks':issuedbooks,'paginationdata':issuedbooks}
	return render(request,'homepage/pastissuedbooks.html',context)

@login_required(login_url='/login/')
def renewdate(request):
	issuedbook = Issue.objects.get(pk=request.POST['pk'])
	issuedbook.return_date = request.POST['renewdate']
	issuedbook.save()
	return redirect('/')

# @login_required(login_url='/login/')
# def searchbooks(request):
# 	books = Book.objects.all()
# 	paginator = Paginator(books, 12)
# 	page = request.GET.get('page')
# 	books = paginator.get_page(page)
# 	# context = getcontext()
# 	context = {}
# 	context['books'] = context['paginationdata'] = books
# 	return render(request,'homepage/searchbooks.html',{'books':books})

def getcontext():
	context = {
		'authors' : Author.objects.all().order_by('author_name'),
		'accmaterials' : AccompanyingMaterials.objects.all(),
		'vendors' : Vendor.objects.all(),
		'bindingtypes':BindingType.objects.all(),
		'doctypes': DocumentType.objects.all(),
		'typeofcollections' : TypeOfCollection.objects.all(),
		'publishers': Publisher.objects.all(),
		'modeofacquisitions':ModeOfAccuisition.objects.all(),
	}
	return context

def booksearchcondition(request,listofval):
	for l in listofval:
		if request.GET.get(l):
			return True
	return False
	# request.GET.get('author')or request.GET.get('publisher')or request.GET.get('title') or request.GET.get('year')	

@login_required(login_url='/login/')
def searchbooks(request):
	books = Book.objects.all().order_by('accession_number')
	listofval = ['author','publisher','title','year','accession_number']
	if (booksearchcondition(request,listofval)):
		if request.GET.get('title'):
			books = books.filter(title__icontains=request.GET.get('title'))
		if request.GET.get('year'):
			books = books.filter(year__icontains=request.GET.get('year'))
		if request.GET.get('publisher'):
			books = books.filter(publisher__pub_name__icontains=request.GET.get('publisher'))
		if request.GET.get('author'):
			books = books.filter(author__author_name__icontains=request.GET.get('author'))
		if request.GET.get('accession_number'):
			books = books.filter(accession_number__icontains=request.GET.get('accession_number'))
	paginator = Paginator(books, 12)
	page = request.GET.get('page')
	books = paginator.get_page(page)
	context = getcontext()
	context['books'] = context['paginationdata'] = books
	return render(request,'homepage/searchbooks.html',context)

homepage/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{% endblock %}</title>
	
	<!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->
	<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> -->
	<!-- <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script> -->
	
	<link href="{% static 'bootstrap5/css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="{% static 'bootstrap5/js/bootstrap.bundle.min.js' %}" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	<script src="{% static 'bootstrap5/jquery.js' %}" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

	<style>
		.nav-item{
			padding: 5px;
		}
	</style>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" style="padding: 1px;">
		<div class="container-fluid">
			<a class="navbar-brand" href="#">Welcome {{ request.user.username }}</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNavDropdown">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item" {% if '/' == request.path or '/issuebook' in request.path or '/viewpast' in request.path %}style="background-color: #2F4F4F"{% endif %}>
						<a class="nav-link active" aria-current="page" href="{% url 'homepage:index' %}"  >Home</a>
					</li>
					<li class="nav-item" {% if '/books/' in request.path %}style="background-color: #2F4F4F"{% endif %}>
						<a class="nav-link active" aria-current="page" href="{% url 'books:index' %}">Books</a>
					</li>
					<li class="nav-item" {% if '/authors/' in request.path %}style="background-color: #2F4F4F"{% endif %}>
						<a class="nav-link active" aria-current="page" href="{% url 'authors:index' %}" >Authors</a>
					</li>

					<li class="nav-item" {% if '/members/' in request.path %}style="background-color: #2F4F4F"{% endif %}>
						<a class="nav-link active" aria-current="page" href="{% url 'members:index' %}" >Members</a>
					</li>
					
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							Other data
						</a>
						<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
							<li>
								<a class="dropdown-item {% if 'publisher' in request.path %}active{% endif %}" aria-current="page" href="{% url 'publisher:index' %}" \>Publisher</a>
							</li>
							<li>
								<a class="dropdown-item {% if 'accompanyingmaterials' in request.path %}active{% endif %}" aria-current="page" href="{% url 'accompanyingmaterials:index' %}">Accompanying Materials</a>
							</li>
							<li>
								<a class="dropdown-item {% if '/vendor/' in request.path %}active{% endif %}" aria-current="page" href="{% url 'vendor:index' %}">Vendor</a>
							</li>
							<li>
								<a class="dropdown-item {% if '/bindingtypes/' in request.path %}active{% endif %}" aria-current="page" href="{% url 'bindingtypes:index' %}">Type of Binding</a>
							</li>
							<li>
								<a class="dropdown-item {% if '/doctypes/' in request.path %}active{% endif %}" aria-current="page" href="{% url 'doctypes:index' %}">Doctype</a>
							</li>
							<li>
								<a class="dropdown-item {% if '/collectiontype/' in request.path %}active{% endif %}" aria-current="page" href="{% url 'collectiontype:index' %}">Type of Collection</a>
							</li>
							<li>
								<a class="dropdown-item {% if '/modeofacqisition/' in request.path %}active{% endif %}" aria-current="page" href="{% url 'modeofacqisition:index' %}">Mode of Acquisition</a>
							</li>
						</ul>
					</li>
				</ul>
				<div>
					<a href="{% url 'login:logoutuser' %}" class="btn btn-outline-danger">Logout</a>
				</div>
			</div>
		</div>
	</nav>
	<div style="height: 80px;">sdf</div>
	{% block body %}
	{% endblock %}
</body>
</html>

homepage/templates/editmodal.html
<div class="modal fade" id="nameModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content text-center">
			<div class="modal-header">
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<form method="post">
					<table class="table">
						{% csrf_token %}
						<tr>
							<td><input type="text" name="name" id="id_name" class="form-control"></td>
							<input type="hidden" name="pk" id="id_pk">
						</tr>
						<tr>
							<td><input type="submit" class="btn btn-outline-success"></td>
						</tr>
					</table>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
	function setname(pk,name){
		$('#id_name').val(name)
		$('#id_pk').val(pk)
	}
</script>

homepage/templates/pagination.html
{% load customfilter %}
<nav aria-label="Page navigation example">
	<ul class="pagination justify-content-center">
		{% if paginationdata.has_previous %}
		<li class="page-item"><a class="page-link" href="?{% url_replace request 'page' paginationdata.previous_page_number %}">Previous</a></li>
		{% else %}
		<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
		{% endif %}
		{% if paginationdata.number|add:'-4' > 1 %}
		<li class="text-dark page-item">
			<a href="?page=1" class="page-link">1</a>
		</li>
		<li>
			<a href="?{% url_replace request 'page' paginationdata.number|add:'-5' %}" class="page-link">&hellip;</a>
		</li>
		{% endif %}
		{% for i in paginationdata.paginator.page_range %}
		{% if paginationdata.number == i %}
		<li class="page-item active">
			<a href="?{% url_replace request 'page' i %}" class="page-link">{{i}}</a>
		</li>
		{% elif i > paginationdata.number|add:'-5' and i < paginationdata.number|add:'5' %}
		<li class="page-item {% if i == paginationdata.number %} active {% endif %}">
			<a href="?{% url_replace request 'page' i %}" class="page-link">{{i}}</a>
		</li>
		{% endif %}
		{% endfor %}
		{% if paginationdata.paginator.num_pages > paginationdata.number|add:'4' %}
		<li class="page-item">
			<a href="?{% url_replace request 'page' paginationdata.number|add:'5' %}" class="page-link">&hellip;</a>
		</li>
		{% if book.number != paginationdata.paginator.num_pages %}
		<li class="text-dark page-item">
			<a href="?{% url_replace request 'page' paginationdata.paginator.num_pages %}" class="page-link">{{ paginationdata.paginator.num_pages }}</a>
		</li>
		{% endif %}
		{% endif %}
		{% if paginationdata.has_next %}
		<li class="page-item"><a class="page-link" href="?{% url_replace request 'page' paginationdata.next_page_number %}">Next</a></li>
		{% else %}
		<li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
		{% endif %}
	</ul>
</nav>